Repository Frozox/ESGI-social-network, pull requests merged in 2022-07, with the labels that each got.

#1 Setup express
  .docker/conf/Web.API/.env.local
  .gitignore
  Makefile
  README.md
  Web.API/.env
  Web.API/.gitignore
  Web.API/app/controllers/HttpCode.js
  Web.API/app/controllers/User.js
  Web.API/app/models/mongo/HttpCode.js
  Web.API/app/models/mongo/db.js
  Web.API/app/models/mongo/index.js
  Web.API/app/models/postgres/User.js
  Web.API/app/models/postgres/db.js
  Web.API/app/models/postgres/index.js
  Web.API/app/routes/routes.js
  Web.API/docker-compose.yml
  Web.API/index.js
  Web.API/package.json
  Web.UI/.gitignore
  Web.UI/docker-compose.yml
Labels: enhancement

#2 Setup front
  .gitignore
  Web.UI/.gitignore
  Web.UI/index.html
  Web.UI/package-lock.json
  Web.UI/package.json
  Web.UI/postcss.config.js
  Web.UI/src/App.css
  Web.UI/src/App.tsx
  Web.UI/src/api/apiUtils.ts
  Web.UI/src/api/auth.axios.ts
  Web.UI/src/assets/images/bg.jpeg
  Web.UI/src/components/Loader.tsx
  Web.UI/src/components/modal.tsx
  Web.UI/src/favicon.svg
  Web.UI/src/index.css
  Web.UI/src/main.tsx
  Web.UI/src/pages/LoginPage.tsx
  Web.UI/src/pages/RegisterPage.tsx
  Web.UI/src/routes/routes.tsx
  Web.UI/src/utils/context/StoreContext.tsx
  Web.UI/src/utils/context/actions/auth.ts
  Web.UI/src/utils/context/actions/loader.ts
  Web.UI/src/utils/context/reducers/auth.ts
  Web.UI/src/utils/context/reducers/loading.tsx
  Web.UI/src/utils/context/reducers/modal.tsx
  Web.UI/src/vite-env.d.ts
  Web.UI/tailwind.config.js
  Web.UI/tsconfig.json
  Web.UI/tsconfig.node.json
  Web.UI/vite.config.ts
  Web.UI/yarn.lock
Labels: enhancement

#3 Remove Yarn Lock
  Web.UI/.gitignore
  Web.UI/yarn.lock
Labels: bug

#4 add dbdiagram and main subject
  helpers/dbdiagram.png
  helpers/main.pdf
Labels: documentation

#5 Feature/chat UI
  Web.UI/.gitignore
  Web.UI/package-lock.json
  Web.UI/src/api/users.axios.ts
  Web.UI/src/components/chat/ChatBox.tsx
  Web.UI/src/components/chat/ChatBoxHeader.tsx
  Web.UI/src/components/chat/ChatBoxMessageItem.tsx
  Web.UI/src/components/chat/ChatBoxMessageList.tsx
  Web.UI/src/components/chat/ChatList.tsx
  Web.UI/src/components/chat/ChatListItem.tsx
  Web.UI/src/components/chat/ChatListWithSearch.tsx
  Web.UI/src/components/chat/ChatSearch.tsx
  Web.UI/src/pages/ChatPage.tsx
  Web.UI/src/routes/routes.tsx
  Web.UI/src/utils/context/StoreContext.tsx
  Web.UI/src/utils/context/actions/users.ts
  Web.UI/src/utils/context/reducers/users.ts
Labels: enhancement

#6 Features database -> develop
  .docker/conf/Web.API/.env.local
  Makefile
  Web.API/.env
  Web.API/.gitignore
  Web.API/app/controllers/User.js
  Web.API/app/controllers/messageChat.js
  Web.API/app/lib/jwt.js
  Web.API/app/models/mongo/messageChat.js
  Web.API/app/models/postgres/User.js
  Web.API/app/models/postgres/db.js
  Web.API/app/routes/routes.js
  Web.API/app/security/verifyToken.js
  Web.API/docker-compose.yml
  Web.API/package.json
  Web.UI/src/api/apiUtils.ts
  Web.UI/src/api/users.axios.ts
  Web.UI/src/pages/LoginPage.tsx
  Web.UI/src/pages/RegisterPage.tsx
  Web.UI/yarn.lock
Labels: enhancement

#8 Add Logger RFC 5424
  .docker/conf/Web.API/.env.local
  Web.API/app/models/mongo/Log.js
  Web.API/app/models/mongo/index.js
  Web.API/app/services/Logger.js
  Web.API/package.json
Labels: enhancement

#11 Features friend
  Makefile
  Web.API/app/controllers/Friend.js
  Web.API/app/controllers/User.js
  Web.API/app/models/postgres/Friend.js
  Web.API/app/models/postgres/User.js
  Web.API/app/models/postgres/index.js
  Web.API/app/routes/routes.js
  Web.UI/src/api/friends.axios.ts
  Web.UI/src/api/users.axios.ts
  Web.UI/src/pages/FriendPage.tsx
  Web.UI/src/pages/LoginPage.tsx
  Web.UI/src/routes/routes.tsx
  Web.UI/src/utils/context/StoreContext.tsx
  Web.UI/src/utils/context/actions/admin.ts
  Web.UI/src/utils/context/actions/auth.ts
  Web.UI/src/utils/context/actions/friends.ts
  Web.UI/src/utils/context/actions/users.ts
  Web.UI/src/utils/context/reducers/admin.ts
  Web.UI/src/utils/context/reducers/auth.ts
  Web.UI/src/utils/context/reducers/friends.ts
  Web.UI/src/utils/context/reducers/users.ts
Labels: enhancement

#15 Update index.ts
  Web.UI/src/utils/helpers/index.ts
Labels: bug

#16 Feature/dashboard
  Web.API/app/controllers/Friend.js
  Web.API/app/controllers/HttpCode.js
  Web.API/app/controllers/Log.js
  Web.API/app/controllers/User.js
  Web.API/app/models/mongo/HttpCode.js
  Web.API/app/models/mongo/Log.js
  Web.API/app/models/mongo/index.js
  Web.API/app/models/postgres/db.js
  Web.API/app/routes/routes.js
  Web.API/app/services/IoHandler.js
  Web.API/app/services/Logger.js
  Web.UI/package.json
  Web.UI/src/api/apiUtils.ts
  Web.UI/src/api/logs.axios.ts
  Web.UI/src/api/users.axios.ts
  Web.UI/src/components/Dashboard.tsx
  Web.UI/src/components/Table.tsx
  Web.UI/src/components/chat/ChatBox.tsx
  Web.UI/src/pages/Admin/AdminAnalyticsPage.tsx
  Web.UI/src/pages/Admin/AdminLogPage.tsx
  Web.UI/src/pages/Admin/AdminPage.tsx
  Web.UI/src/pages/FriendPage.tsx
  Web.UI/src/routes/routes.tsx
  Web.UI/src/utils/context/actions/admin.ts
  Web.UI/src/utils/context/actions/auth.ts
  Web.UI/src/utils/context/actions/friends.ts
  Web.UI/src/utils/context/actions/user.ts
  Web.UI/src/utils/context/actions/users.ts
  Web.UI/src/utils/helpers/jsxhelpers.tsx
  Web.UI/yarn.lock
Labels: enhancement

#20 Add button to start conversation with friend
  Web.UI/index.html
  Web.UI/package.json
  Web.UI/src/components/Dashboard.tsx
  Web.UI/src/components/Dropdown.tsx
  Web.UI/src/components/SideBar.tsx
  Web.UI/src/components/chat/ChatListWithSearch.tsx
  Web.UI/src/pages/Admin/WarningManagerPage.tsx
  Web.UI/src/pages/UserProfilePage.tsx
  Web.UI/src/routes/routes.tsx
Labels: enhancement

#21 Fix/before demo
  Web.API/app/models/postgres/User.js
  Web.UI/src/api/users.axios.ts
  Web.UI/src/components/Dashboard.tsx
  Web.UI/src/components/Form.tsx
  Web.UI/src/components/FriendList.tsx
  Web.UI/src/components/MultiSelectButtons.tsx
  Web.UI/src/components/SideBar.tsx
  Web.UI/src/components/chat/ChatBox.tsx
  Web.UI/src/components/chat/ChatList.tsx
  Web.UI/src/components/chat/ChatListWithSearch.tsx
  Web.UI/src/components/chat/ChatSearch.tsx
  Web.UI/src/pages/Admin/AdminAnalyticsPage.tsx
  Web.UI/src/pages/UserProfilePage.tsx
  Web.UI/src/routes/routes.tsx
  Web.UI/src/utils/context/actions/auth.ts
  Web.UI/src/utils/context/actions/friends.ts
  Web.UI/src/utils/context/reducers/user.ts
Labels: bug
